### ISSUE TITLE
Mysterious Glitch That Causes P2 forces to have Sonic's Abilities

### ISSUE THREAD

**Issue by KirbyJoe** [thesupersonic16/mania-mod-loader#10]
I recently have a glitch that forces to enable "P2 Has Sonic's Abilities" on the Codes section. When I use the Mod Manager, I've noticed that "P2 Has Sonic's Abilities" is always checked. I also seen the same code on the bottom of the list of codes, which cannot be unchecked. I tried to modify the ManiaModLoader.ini on the mods folder but it won't fixed correctly. How can I fix this?

![mysterious maniamodmanager glitch 1](https://user-images.githubusercontent.com/20151551/39963507-06fb69c4-56a8-11e8-8218-ff21ab4253b2.PNG)

**Comment by KirbyJoe** [comment]
Attention: This is a glitch of the mod called "[Sonic 2 Beta Sprites](https://gamebanana.com/skins/162780)" that I found on GameBanana. I'm very interested about the classic experience in Sonic Mania and I have many mods that changes the graphics and musics into the ones of the classic games. I try to ask the creator of the mod and fix this issue.

**Comment by thesupersonic16** [comment]
The creator made his mod to force it to be enabled. This isn't an issue.
