### ISSUE TITLE
Missing codes

### ISSUE THREAD

**Issue by Araraura** [thesupersonic16/mania-mod-loader#2]
Most of the codes are missing

**Comment by thesupersonic16** [comment]
Yeah, I know, It takes time to find codes, I just don't really feel like completing the list, I'll try get more codes in though.

**Comment by thesupersonic16** [comment]
Also you can update the code list by just downloading https://github.com/thesupersonic16/mania-mod-loader/blob/master/data/Codes.xml and saving it in `Sonic Mania\mods\Codes.xml`

**Comment by thesupersonic16** [comment]
I'm gonna close this issue now as I have most of them.
