### ISSUE TITLE
Mods from GameBanana don't install

### ISSUE THREAD

**Issue by MegaSuperab** [thesupersonic16/mania-mod-loader#6]
When I try to install a mod from game GameBanana, it downloads the ZIP file correctly, however it doesn't detect the mod.ini file, even if it's there. When I manually add it, the mod installs but only the mod.ini file is there (probably not related to the issue but still).
![capture](https://user-images.githubusercontent.com/7158344/34075858-40319638-e299-11e7-81a4-dbd057d74056.PNG)

**Comment by thesupersonic16** [comment]
Sorry for the issues it has caused, Please try this and let me know if this fixes your issue.
[ManiaModManager.zip](https://github.com/thesupersonic16/mania-mod-loader/files/1565301/ManiaModManager.zip)

**Comment by MegaSuperab** [comment]
Works now, thanks! :)
