### ISSUE TITLE
Gamebanana mods not downloading because of mod.ini

### ISSUE THREAD

**Issue by BoeGitHub** [thesupersonic16/mania-mod-loader#7]
Whenever i download a mod off of gamebanana it always says Unable to locate mod.ini in mods\.updates\(Mod Name). Can you please help fix this?
![image](https://user-images.githubusercontent.com/24979807/34076276-8bc3c516-e2ae-11e7-9b78-6f9793d4621a.png)

**Comment by thesupersonic16** [comment]
Fixed on the newest Release, Issue was that I forgot to update ModManagerCommon
